/**
 * islands.data.js
 *
 * Configurable details for the 6 interactive islands representing Bipolar Disorder topics.
 */

export const islandsData = [
  {
    id: 1,
    title: "The Still Island",
    subtitle: "Definition",
    route: "/island/1",
    position: [-14, 0, -8],
    color: "#05395E",
    accentColor: "#91BFF6",
    scale: 2.1,
    elevation: 1.5,
    image: "/island_still.png",
    heroImage: "/hero_still_island.png",
    introText: "Bipolar disorder is a mental health condition that causes extreme shifts in mood, energy, sleep, and behavior.",
    mainContent: [
      "According to the World Health Organization, more than 40 million people worldwide live with bipolar disorder.",
      "The disorder affects how the brain regulates mood, energy, sleep, and decision-making.",
      "Misdiagnosis occurs in 69% of patients at their first evaluation, because the condition is frequently mistaken for depression.",
    ],
    endingLine: "Some storms cannot be seen from the shore.",
  },
  {
    id: 2,
    title: "The Burning Island",
    subtitle: "Mania",
    route: "/island/2",
    position: [-8, 0, 10],
    color: "#C05118",
    accentColor: "#F0813A",
    scale: 1.8,
    elevation: 1.1,
    image: "/island_burning.png",
    heroImage: "/hero_burning_island.png",
    introText: "Mania is a state of abnormally elevated mood and energy that can last for days or weeks.",
    mainContent: [
      "Common symptoms include reduced need for sleep, rapid speech, impulsive decisions, inflated self-esteem, and risky behavior.",
      "Severe manic episodes may include psychosis, affecting a person's ability to recognize reality.",
      "Most of the time, people in manic states are unaware of the negative consequences of their actions.",
      "Studies show many individuals experiencing mania do not recognize the episode while it is happening.",
    ],
    endingLine: "Not every bright light is safe to follow.",
  },
  {
    id: 3,
    title: "The Sunken Island",
    subtitle: "Depression",
    route: "/island/3",
    position: [6, 0, -12],
    color: "#1a3a5c",
    accentColor: "#DFE1E6",
    scale: 2.3,
    elevation: 2.0,
    image: "/island_sunken.png",
    heroImage: "/hero_sunken_island.png",
    introText: "Bipolar depression is more than sadness. It can affect memory, concentration, movement, sleep, appetite, and the ability to function.",
    mainContent: [
      "Research tracking patients over one year found that people with bipolar disorder spend approximately 36% of their time in depressive states.",
      "Three times more than in manic or hypomanic states combined.",
      "Depressive episodes are strongly associated with disability, reduced quality of life, and increased risk of suicidal thoughts and behavior.",
    ],
    endingLine: "Some people drown quietly.",
  },
  {
    id: 4,
    title: "The Twin Islands",
    subtitle: "Bipolar I & Bipolar II",
    route: "/island/4",
    position: [15, 0, 4],
    color: "#5184C0",
    accentColor: "#DFE1E6",
    scale: 1.9,
    elevation: 1.4,
    image: "/island_twin.png",
    heroImage: "/hero_twin_island.png",
    introText: "The main difference between Bipolar I and Bipolar II is the severity of the manic episodes.",
    mainContent: [
      "Bipolar I involves full manic episodes that can become severe enough to disrupt daily life, require hospitalization, or include psychotic symptoms such as delusions.",
      "Bipolar II involves hypomania — a milder form of mania that may appear as increased energy or productivity without requiring hospital care — combined with long-lasting depressive episodes.",
    ],
    endingLine: "Not every storm arrives the same way.",
  },
  {
    id: 5,
    title: "The Root Island",
    subtitle: "Causes",
    route: "/island/5",
    position: [2, 0, 12],
    color: "#05395E",
    accentColor: "#91BFF6",
    scale: 2.0,
    elevation: 1.3,
    image: "/island_root.png",
    heroImage: "/hero_root_island.png",
    introText: "Research shows genetics play a major role. People with a close family history of bipolar disorder are significantly more likely to develop it themselves.",
    mainContent: [
      "Brain imaging studies also show differences in areas linked to emotional regulation, stress response, and impulse control.",
      "Trauma, sleep disruption, and substance use can trigger or worsen episodes over time.",
    ],
    endingLine: "What appears suddenly often begins far below the surface.",
  },
  {
    id: 6,
    title: "The Lighthouse Island",
    subtitle: "Treatment & Recovery",
    route: "/island/6",
    position: [-20, 0, 5],
    color: "#314e7a",
    accentColor: "#5184C0",
    scale: 1.6,
    elevation: 1.0,
    image: "/island_lighthouse.png",
    heroImage: "/hero_lighthouse_island.png",
    introText: "Bipolar disorder cannot currently be cured, but it can be managed successfully with long-term treatment.",
    mainContent: [
      "Studies show that consistent treatment greatly reduces relapse and hospitalization rates.",
      "Medication, therapy, stable sleep, and social support help many people regain long-term stability.",
      "Early diagnosis and consistent treatment improve long-term functioning, relationships, and quality of life.",
    ],
    endingLine: "Recovery is not perfection. It is learning how to continue through the waves.",
  },
];
