import { useRef, useEffect } from 'react'
import { motion } from 'framer-motion'
import './TextStory.css'

/**
 * TextStory
 * Fullscreen image with staggered paragraph reveal.
 * Background image subtly drifts (Ken Burns effect).
 * Each paragraph fades + slides in on mount.
 */
export default function TextStory({ story }) {
  const scrollRef = useRef(null)

  // Auto-scroll feature removed as it prevents manual scrolling
  useEffect(() => {
    // Scrolling is now purely manual
  }, [])

  return (
    <div className="text-story">
      {/* Fullscreen background image */}
      <div className="text-bg-wrap">
        <motion.div
          className="text-bg-img"
          style={{ backgroundImage: `url("${story.image}")` }}
          animate={{
            scale: [1, 1.06],
            x: [0, -12],
          }}
          transition={{
            duration: 25,
            repeat: Infinity,
            repeatType: 'mirror',
            ease: 'linear',
          }}
        />
        {/* Dark vignette */}
        <div className="text-vignette" />
        {/* Color wash */}
        <div className="text-color-wash" style={{ background: story.color + '15' }} />
      </div>

      {/* Scrollable content */}
      <div className="text-content-scroll" ref={scrollRef}>
        <div className="text-content-inner">

          {/* Title block */}
          <motion.div
            className="text-title-block"
            initial={{ opacity: 0, y: 40 }}
            animate={{ opacity: 1, y: 0 }}
            transition={{ duration: 1.2, ease: [0.22, 1, 0.36, 1] }}
          >
            <div className="text-badge" style={{ color: story.color }}>
              ✦ Written Story
            </div>
            <h2 className="text-main-title">{story.title}</h2>
            <p className="text-subtitle">{story.subtitle}</p>
            <div className="text-divider" style={{ background: story.color }} />
          </motion.div>

          {/* Hero Image */}
          {story.image && (
            <motion.div 
              className="text-hero-image-container"
              initial={{ opacity: 0, scale: 0.95 }}
              animate={{ opacity: 1, scale: 1 }}
              transition={{ duration: 1, delay: 0.2, ease: "easeOut" }}
            >
              <img 
                src={story.image} 
                alt={story.title} 
                style={{
                  width: '100%',
                  maxHeight: '400px',
                  objectFit: 'cover',
                  borderRadius: '12px',
                  boxShadow: '0 10px 30px rgba(0,0,0,0.5)',
                  marginBottom: '8px'
                }} 
              />
              <p style={{
                fontSize: '0.8rem',
                color: 'rgba(255, 255, 255, 0.6)',
                textAlign: 'center',
                marginBottom: '16px',
                fontStyle: 'italic'
              }}>
                Note: This image is generated by AI and is not a real photograph.
              </p>
            </motion.div>
          )}

          {/* Paragraphs */}
          <div className="text-paragraphs">
            {story.paragraphs.map((para, i) => (
              <motion.p
                key={i}
                className={`text-para${i === story.paragraphs.length - 1 ? ' text-para--quote' : ''}`}
                initial={{ opacity: 0, y: 28 }}
                animate={{ opacity: 1, y: 0 }}
                transition={{
                  duration: 0.9,
                  delay: 0.4 + i * 0.18,
                  ease: [0.22, 1, 0.36, 1],
                }}
                style={i === story.paragraphs.length - 1 ? { borderLeftColor: story.color } : {}}
              >
                {para}
              </motion.p>
            ))}
          </div>

          {/* End mark */}
          <motion.div
            className="text-end-mark"
            initial={{ opacity: 0, scale: 0.8 }}
            animate={{ opacity: 1, scale: 1 }}
            transition={{ duration: 1, delay: 0.4 + story.paragraphs.length * 0.18 }}
          >
            <div className="text-end-line" style={{ background: story.color }} />
            <span style={{ color: story.color }}>∼</span>
            <div className="text-end-line" style={{ background: story.color }} />
          </motion.div>

        </div>
      </div>
    </div>
  )
}
